import{a as q,S as v,i as n}from"./assets/vendor-Bt_EzQve.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();async function g(i,t=1){try{const{data:r}=await q("https://pixabay.com/api/",{params:{key:"52807659-bebfa0ce69a97bf76a6d524af",q:i,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}});return r}catch{iziToast.error({title:"Error",message:"Something went wrong while fetching data. Please try again later!",timeout:4e3,position:"topRight"})}}const h=document.querySelector(".gallery"),y=document.querySelector(".loader"),p=document.querySelector(".button"),P=new v(".gallery a",{captionsData:"alt",captionDelay:250});function b(i){const t=i.map(({webformatURL:r,largeImageURL:s,tags:e,likes:o,views:a,comments:w,downloads:S})=>`<li class="gallery-item">
        <a href="${s}" class="gallery-link">
          <img src="${r}" alt="${e}" class="gallery-image" />
        </a>
        <div class="info">
          <p class="info-item"><b>Likes</b> ${o}</p>
          <p class="info-item"><b>Views</b> ${a}</p>
          <p class="info-item"><b>Comments</b> ${w}</p>
          <p class="info-item"><b>Downloads</b> ${S}</p>
        </div>
      </li>`).join("");h.insertAdjacentHTML("beforeend",t),P.refresh()}function $(){h.innerHTML=""}function L(){y.classList.remove("is-hidden")}function u(){y.classList.add("is-hidden")}function O(){p.classList.remove("js-hidden")}function l(){p.classList.add("js-hidden")}const f=document.querySelector(".form"),R=f.querySelector(".form-input"),E=document.querySelector(".button");E.addEventListener("click",B);let c="",d=1,m=0;f.addEventListener("submit",M);async function M(i){i.preventDefault();const t=R.value.trim();if(!t){n.warning({title:"Oops!",message:"Please enter a search term",timeout:3e3,position:"topRight"});return}t!==c&&(d=1,c=t,$()),L(),l();try{u();const r=await g(c,d),{hits:s,totalHits:e}=r;if(m=e,s.length===0){n.error({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!",timeout:3e3,position:"topRight"}),l();return}b(s),s.length<m?O():l(),f.reset()}catch(r){console.log(r),n.error({title:"Error",message:"Failed to load more images. Please try again later.",timeout:3e3,position:"topRight"})}finally{u()}}async function B(){d+=1,L();try{u();const i=await g(c,d),{hits:t}=i;if(t.length===0){l(),n.error({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!",timeout:3e3,position:"topRight"});return}b(t);const r=document.querySelector(".gallery-item");if(r){const e=r.getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}document.querySelectorAll(".gallery-item").length>=m&&(l(),n.info({title:"End of results",message:"We're sorry, but you've reached the end of search results.",timeout:3e3,position:"topRight"}))}catch(i){console.error(i)}finally{u()}}
//# sourceMappingURL=index.js.map
