import{a as w,S as v,i as a}from"./assets/vendor-Bt_EzQve.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();async function m(i,t=1){try{const{data:o}=await w("https://pixabay.com/api/",{params:{key:"52807659-bebfa0ce69a97bf76a6d524af",q:i,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}});return o}catch{iziToast.error({title:"Error",message:"Something went wrong while fetching data. Please try again later!",timeout:4e3,position:"topRight"})}}const f=document.querySelector(".gallery"),g=document.querySelector(".loader"),h=document.querySelector(".button"),P=new v(".gallery a",{captionsData:"alt",captionDelay:250});function p(i){const t=i.map(({webformatURL:o,largeImageURL:s,tags:e,likes:r,views:n,comments:S,downloads:q})=>`<li class="gallery-item">
        <a href="${s}" class="gallery-link">
          <img src="${o}" alt="${e}" class="gallery-image" />
        </a>
        <div class="info">
          <p class="info-item"><b>Likes</b> ${r}</p>
          <p class="info-item"><b>Views</b> ${n}</p>
          <p class="info-item"><b>Comments</b> ${S}</p>
          <p class="info-item"><b>Downloads</b> ${q}</p>
        </div>
      </li>`).join("");f.insertAdjacentHTML("beforeend",t),P.refresh()}function $(){f.innerHTML=""}function y(){g.classList.remove("is-hidden")}function b(){g.classList.add("is-hidden")}function O(){h.classList.remove("js-hidden")}function u(){h.classList.add("js-hidden")}const d=document.querySelector(".form"),R=d.querySelector(".form-input"),E=document.querySelector(".button");E.addEventListener("click",B);let l="",c=1,L=0;d.addEventListener("submit",M);function M(i){i.preventDefault();const t=R.value.trim();if(!t){a.warning({title:"Oops!",message:"Please enter a search term",timeout:3e3,position:"topRight"});return}t!==l&&(c=1,l=t,$()),y(),m(l,c).then(o=>{b();const{hits:s,totalHits:e}=o;if(L=e,s.length===0){a.error({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!",timeout:3e3,position:"topRight"}),u();return}p(s),O(),d.reset()}).catch(o=>{console.log(o),a.error({title:"Error",message:"Failed to load more images. Please try again later.",timeout:3e3,position:"topRight"})})}function B(){c+=1,y(),m(l,c).then(i=>{b();const{hits:t}=i;if(t.length===0){u(),a.error({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!",timeout:3e3,position:"topRight"});return}p(t);const o=document.querySelector(".gallery-item");if(o){const e=o.getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}document.querySelectorAll(".gallery-item").length>=L&&(u(),a.info({title:"End of results",message:"We're sorry, but you've reached the end of search results.",timeout:3e3,position:"topRight"}))}).catch(i=>{console.error(i)})}
//# sourceMappingURL=index.js.map
